version: "3"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.11.1/24

services:
  proxy:
    image: nginx:1.21.1
    restart: always
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache:/data/cache
    logging:
      options:
        max-size: "100m"
        max-file: "3"
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - web
      - jupyter-proxy
      
  web:
    image: illgrenoble/visa-web:${VISA_VERSION:-2.1}
    restart: always

  api:
    image: illgrenoble/visa-api-server:${VISA_VERSION:-2.1}
    restart: always
    volumes:
      - /var/log/visa:/var/log/visa
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VISA_SERVER_PORT=8086
      - VISA_VDI_PORT=8087
    env_file: .env
    links:
      - accounts

  jupyter-proxy:
    image: illgrenoble/visa-jupyter-proxy:${VISA_VERSION:-2.1}
    restart: always
    links:
      - api
    environment:
      - VISA_JUPYTER_PROXY_SERVER_PORT=8088
      - VISA_JUPYTER_PROXY_API_HOST=api
      - VISA_JUPYTER_PROXY_API_PORT=8086
    env_file: .env

  accounts:
    image: illgrenoble/visa-accounts:${VISA_VERSION:-2.1}
    restart: always
    volumes:
      - ./providers/attribute-provider.js:/app/accountAttributeProviders/attribute-provider.js
    ports:
      - 8089:8089
    environment:
      - VISA_ACCOUNTS_SERVER_PORT=8089
    env_file: .env
